-- Költségnyilvántartó v4.1 - Teljes Supabase SQL Táblaséma
-- Futtasd le ezt a szkriptet a Supabase SQL Editor-jában!

-- 1. ITEMS (Kategóriák)
CREATE TABLE IF NOT EXISTS items (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    color TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Mindenki elérheti" ON items;
CREATE POLICY "Mindenki elérheti" ON items FOR ALL USING (true) WITH CHECK (true);

-- 2. MONTHS (Aktív Hónapok)
CREATE TABLE IF NOT EXISTS months (
    month TEXT PRIMARY KEY,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE months ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Mindenki elérheti" ON months;
CREATE POLICY "Mindenki elérheti" ON months FOR ALL USING (true) WITH CHECK (true);

-- 3. ENTRIES (Bejegyzések / Rész-tételek)
CREATE TABLE IF NOT EXISTS entries (
    id TEXT PRIMARY KEY,
    "cellKey" TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    currency TEXT DEFAULT 'HUF',
    "paymentMethod" TEXT DEFAULT 'Kártya',
    note TEXT,
    color TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Mindenki elérheti" ON entries;
CREATE POLICY "Mindenki elérheti" ON entries FOR ALL USING (true) WITH CHECK (true);

-- 4. TEMPLATES (Sablonok)
CREATE TABLE IF NOT EXISTS templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    amount NUMERIC,
    currency TEXT DEFAULT 'HUF',
    comment TEXT,
    category TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Mindenki elérheti" ON templates;
CREATE POLICY "Mindenki elérheti" ON templates FOR ALL USING (true) WITH CHECK (true);

-- 5. REMINDERS (Határidők)
CREATE TABLE IF NOT EXISTS reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    currency TEXT DEFAULT 'HUF',
    due_date TEXT NOT NULL,
    frequency TEXT DEFAULT 'once',
    completed BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Mindenki elérheti" ON reminders;
CREATE POLICY "Mindenki elérheti" ON reminders FOR ALL USING (true) WITH CHECK (true);

-- 6. INCOMINGS (Bejövő utalások)
CREATE TABLE IF NOT EXISTS incomings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender TEXT NOT NULL,
    date TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    comment TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE incomings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Mindenki elérheti" ON incomings;
CREATE POLICY "Mindenki elérheti" ON incomings FOR ALL USING (true) WITH CHECK (true);

-- 7. INCOMING_SENDERS (Bejövő küldők)
CREATE TABLE IF NOT EXISTS incoming_senders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE incoming_senders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Mindenki elérheti" ON incoming_senders;
CREATE POLICY "Mindenki elérheti" ON incoming_senders FOR ALL USING (true) WITH CHECK (true);

-- 8. DELETED_RECORDS (Törölt rekordok követése - Tombstone)
CREATE TABLE IF NOT EXISTS deleted_records (
    id TEXT PRIMARY KEY,
    record_id TEXT NOT NULL,
    table_name TEXT NOT NULL,
    deleted_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE deleted_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Mindenki elérheti" ON deleted_records;
CREATE POLICY "Mindenki elérheti" ON deleted_records FOR ALL USING (true) WITH CHECK (true);
